# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-03-08 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Subscriber')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='newsletteropen',
            unique_together=set([('subscriber', 'newsletter')]),
        ),
    ]
