# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-03-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20250308_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
