# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-03-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20250309_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
