# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-03-10 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20250309_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='html_content',
            field=models.TextField(error_messages={'required': b'This field is required'}),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='send_time',
            field=models.DateTimeField(blank=True, error_messages={'invalid': 'invalid_date_time'}, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(error_messages={'required': b'This field is required'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='birthday',
            field=models.DateField(error_messages={'required': b'This field is required'}),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'invalid_email', 'required': b'This field is required', 'unique': b'Email already exists'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='firstname',
            field=models.CharField(error_messages={'required': b'This field is required'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='lastname',
            field=models.CharField(error_messages={'required': b'This field is required'}, max_length=100),
        ),
    ]
